### ISSUE TITLE
Actualización de estilo

### ISSUE THREAD

**Issue by leabravo** [leetdatageek/org-zettelkasten#2]
- [ ] Ajustar ancho de elemento a display ~14'

```css
#content > [class^="outline"] {
    width: 50vw;
}

#table-of-contents {
    width: 20vw;
    text-align: left;
}
```

- [ ] Crear media query para pantallas chicas
